version: '3'

services:
  web:
    image: brucewang1/microservicecalculator:1.1.1
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: on-failure
